#Chinmay Keskar , Harmehar Singh
#November 29th, 2019
#Hangman - Automobile Variation
#How to build a hangman game with a car theme?

import random #importing random module
right= 0
lives = 5 

#Chinmay
#Defining a function called startmenu that gives allows the user to help, start or quit
def startmenu():
  helpmenu = input('Welcome to Hangman - Automobile Edition! Press s to start, q to quit, or h for help:')
  start_options = ['s','q','h']
  if helpmenu not in start_options:
    print('Invalid input - please enter an option given above.')
  return helpmenu

#defining all global variables
lives = 5
right = 0

#Chinmay
#defining a function called rulesmenu that prints the rules of the game
def rulesmenu():
    print(' ')
    print('Welcome to Automobile Hangman!')
    print('The Rules are that of Classic Hangman.')
    print('You have to keep guessing at a random car-related word generated by the program.')
    print('You win by getting all of the words correct, but lose if you get five incorrect.')
    print('A single hint is available each game if needed.')
    print('If you get three letters wrong, the hint will be offered again.')
    print('Good Luck!')
    print(' ')

#Chinmay
#defining a function called endmenu that prints user a farewell message
def endmenu():
  print('Thank you for playing Automobile Hangman! Goodbye Now.')
  

#Chinmay
#defining a function called get_word that gets passed wordlist
#assigns word a random element from wordlist
def get_word(wordlist): 
  word = random.choice(wordlist)
  return word

#Function that is passed user guess and sliced word
# makes the answer equal to the guess in sliceword
#chinmay
def check_hint(guess, sliceword):
  answer = guess in sliceword 
  return answer

#defining a function that asks the user to input y or n for hints
#chinmay
def ask_hint():
  user_input= input('Hint: y for yes or n for no: ')
  return user_input

#Chinmay
#defining a function called get_hints that gets passed the word
def get_hints(word): 
  if word == 'wheel':
    print('The ____ on the bus...')
  elif word == 'axle' :
    print('This part bears the weight of the car and its contents.')
  elif word == 'bumper':
    print('This Prevents damage in the case of a collision.')
  elif word == 'piston':
    print('This produces the energy of the engine.')
  elif word=='engine':
    print('This converts chemical energy into kinetic energy.')
  elif word == 'accelerator':
    print('This is also known as the gas pedal.')
  elif word == 'exhaust':
    print('This part contributes to global warming.')
  elif word == 'transmission':
    print('This makes sure that the right amount of power go into the tires.')
  elif word == 'ignition':
    print('This ignites the fuel in the cylinder of a car and you use it start a car.')
  elif word == 'speedometer':
    print('This displays the cars rate of displacement.')
  elif word == 'radiator':
    print('These exchange the heat in a cars combustion chamber to cool it down.')
  else:
    print("you've chosen to go without hints - good luck.")

#Chinmay
#calling a function called wordslicer that is passed the word.
#it slices the word and returns it as sliceword
def wordslicer(word):
  sliceword = [word[0:1], word[1:2], word[2:3], word[3:4], word[4:5],word[5:6], word[6:7], word[7:8], word[8:9], word[9:10], word[10:11],word[11:12]]   
  return sliceword 

#Harmehar
#defining a function called check_length that is passed the word
#it returns the length of the word as wordlength
def check_length(word):
  wordlength= len(word)
  return wordlength

#harmehar
#defining a function called get_guess  
def get_guess():
  while True:    
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    userInput = input("Please enter your guess:")
    if userInput == '' or userInput == ' ':
        print("Please enter valid input.")
    elif userInput not in alphabet:
        print("You must enter an alphabetic character.")
  return userInput       

#Harmehar
def ASCII_hangman():
  hangman_pics = ['''
   +---+

   |   |

       |

       |

       |

       |
 =========''', '''
   +---+
   |   |

   O   |

       |

       |

       |
 =========''', '''
   +---+

   |   |

   O   |

  /|  |

       |

       |
 =========''', '''
   +---+

   |   |

   O   |

  /|\  |

       |

       |
 =========''', '''
   +---+

   |   |

   O   |

  /|\  |

  /    |

       |
 =========''', '''
   +---+

   |   |

   O   |

  /|\  |

  / \ |

       |
 ========='''] 
  return hangman_pics

#Harmehar
#Defining a function called correct_guess
#This function updates the variable 'right' each time the guess is correct
def correct_guess(guess,word,wordlength, hangman_pics,right, options):
  if choice== True:        
    print('correct.')
    print(hangman_pics[0])
    right +=1
    print(right)
  if right == wordlength:
    print('You won!' + ' ' + 'the word was:' + word)
    startmenu() 
  return options 
#Chinmay
#defining a function called wrong guess that gets passed the guess, word, wordlength, lives, letters, and the hangman pics
#it prints each picture as the lives get lower, then returns to the start menu once all the lives deplete
def wrong_guess(guess,word,wordlength,lives,letters, hangman_pics, options):   
  if lives==4:
    print('Wrong.')
    print(hangman_pics[1])
  elif lives== 3:
    print('Wrong again. The man is losing time.')
    print(hangman_pics[2])       
  elif lives== 2:
    print('Nope. Keep trying, you still have time.')
    print(hangman_pics[3]) 
    if user_input != 'y':
      print("You got three letters wrong! Are you sure you don't need the hint?")
      x = ask_hint()
      if x == 'y':
        get_hints(word)
      elif x != 'y':
        print('Ok then. Proceed.')
  elif lives== 1:
    print('You have one last chance.')
    print(hangman_pics[4])       
  elif lives== 0:
    print('The man is gone. You lost.')
    print(hangman_pics[5])
    startmenu()  
    options = False   
  return options  

#below part done by Harmehar
options= True
while options:
  hangman= ASCII_hangman() 
  lives= 5
  wordlist = ['wheel','axle','bumper','piston','engine','accelerator','exhaust','transmission','ignition','speedometer','radiator']
  helpmenu = startmenu()
  if helpmenu == 'h':
    rulesmenu()   
  elif helpmenu == 's':
    word= get_word(wordlist)
    user_input= ask_hint()
    if user_input== 'y':  
      hint = get_hints(word)
    elif user_input== 'n':
      print('Please carry on')
    else:
      print('Invalid input')
    letters= wordslicer(word)
    wordlength= len(word)
    create = True
    while create :
      guess = get_guess()
      choice = guess in letters   
      if choice== True:
        options = correct_guess(guess,word,wordlength, hangman,right, options)
        right +=1
      elif choice == False:
        lives-= 1          
        options= wrong_guess(guess,word,wordlength,lives,letters, hangman, options)
        if lives==0:
          create= False          
  elif helpmenu == 'q':
    endmenu()
    options= False     



